/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SmartContractPruebaTecnicaAbi } from "./SmartContractPruebaTecnicaAbi";
export * as factories from "./factories";
export { SmartContractPruebaTecnicaAbi__factory } from "./factories/SmartContractPruebaTecnicaAbi__factory";
