/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SmartContractPruebaTecnicaAbiInterface extends Interface {
  getFunction(
    nameOrSignature: "balanceDecrease" | "balanceForUsers" | "increaseBalance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceDecrease",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceForUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "balanceDecrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceForUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseBalance",
    data: BytesLike
  ): Result;
}

export interface SmartContractPruebaTecnicaAbi extends BaseContract {
  connect(runner?: ContractRunner | null): SmartContractPruebaTecnicaAbi;
  waitForDeployment(): Promise<this>;

  interface: SmartContractPruebaTecnicaAbiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceDecrease: TypedContractMethod<[], [void], "nonpayable">;

  balanceForUsers: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  increaseBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceDecrease"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceForUsers"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "increaseBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
