/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SmartContractPruebaTecnicaAbi,
  SmartContractPruebaTecnicaAbiInterface,
} from "../SmartContractPruebaTecnicaAbi";

const _abi = [
  {
    inputs: [],
    name: "balanceDecrease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceForUsers",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "increaseBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SmartContractPruebaTecnicaAbi__factory {
  static readonly abi = _abi;
  static createInterface(): SmartContractPruebaTecnicaAbiInterface {
    return new Interface(_abi) as SmartContractPruebaTecnicaAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SmartContractPruebaTecnicaAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SmartContractPruebaTecnicaAbi;
  }
}
